version: 0.0
os: linux
files:
  - source: ./server
    destination: /home/bitnami/oostaoo
hooks:
  BeforeInstall:
    - location: scripts/install_node_modules.sh
      runas: root
  ApplicationStart:
    - location: scripts/launch_oostaoo.sh
      timeout: 300
      runas: root